name: Deploy to Hugging Face via SSH (passphrase key)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Install key and unlock with passphrase
        env:
          KEY: ${{ secrets.HF_SSH_KEY }}
          PASSPHRASE: ${{ secrets.HF_SSH_PASSPHRASE }}
        run: |
          set -e
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          printf "%s\n" "$KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          # create minimal askpass script
          printf '#!/usr/bin/env bash\necho "$PASSPHRASE"\n' > /tmp/askpass.sh
          chmod +x /tmp/askpass.sh

          eval "$(ssh-agent -s)"
          SSH_ASKPASS=/tmp/askpass.sh DISPLAY=:0 setsid ssh-add ~/.ssh/id_ed25519

          ssh-keyscan huggingface.co >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to Hugging Face Space
        run: |
          git remote add hf git@huggingface.co:spaces/daniellegauthier/RGB-Root-Matriz-Color-Plotter
          git push -f hf main
