name: Deploy to Hugging Face via SSH

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      # Load your private key into an SSH agent (no echo/heredoc quirks)
      - name: Start SSH agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.HF_SSH_KEY }}

      - name: Trust huggingface.co host key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan huggingface.co >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to Hugging Face Space
        run: |
          git remote add hf git@huggingface.co:spaces/daniellegauthier/RGB-Root-Matriz-Color-Plotter
          git push -f hf main
